#! /usr/bin/env bash
#
# Look through libraries and find a name for the given
# uniqueid. Searches classes and methods at the moment.
#

MULLE_EXECUTABLE_VERSION=0.9.1

MULLE_EXECUTABLE_FUNCTIONS_MIN="3.9"
MULLE_EXECUTABLE_FUNCTIONS_MAX="4"


usage()
{
   cat <<EOF >&2
Usage:
   ${MULLE_EXECUTABLE} [options] <class>

   Print a class-coverage.csv line for a class or category. If you also specify
   a method with -m then a method-coverage.csv line will be printed.

Options:
   --method <name>   : specify method
   --category <name> : specify category
EOF

   core_technical_option_usage | sort >&2

   exit 1
}


main()
{
   local LIB_PATH

   local OPTION_SELECTOR="NO"

   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      # your option handling
      case "$1" in
         --version)
            echo "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         -c|--category)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift

            CATEGORY="$1"
         ;;

         -m|--method)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift

            METHOD="$1"
         ;;

         -h|--help)
            usage
         ;;

         -*)
            fail "unknown option $1"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}"

   local uniqueid

   [ $# -ne 1 ] && usage
   CLASS="$1"

   # prefer sibling mulle-objc-lista
   if [ -z "${MULLE_OBJC_UNIQUEID}" ]
   then
      MULLE_OBJC_UNIQUEID="${0%/*}/mulle-objc-uniqueid"
      if [ ! -x "${MULLE_OBJC_UNIQUEID}" ]
      then
         MULLE_OBJC_UNIQUEID="${MULLE_OBJC_UNIQUEID:-`command -v mulle-objc-uniqueid`}"
         [ -z "${MULLE_OBJC_UNIQUEID}" ] && fail "mulle-objc-uniqueid not in PATH"
      fi
   fi

   CLASSID="`"${MULLE_OBJC_UNIQUEID}" "${CLASS}"`"

   if [ ! -z "${CATEGORY}" ]
   then
      CATEGORYID="`"${MULLE_OBJC_UNIQUEID}" "${CATEGORY}"`"
   fi

   if [ -z "${METHOD}" ]
   then
      echo "${CLASSID};${CLASS};${CATEGORYID};${CATEGORY}"
      return 0
   fi

   case "${METHOD}" in
      -*)
         PREFIX="-"
      ;;

      +*)
         PREFIX="+"
      ;;

      *)
         fail "Method must have - or + prefix"
      ;;
   esac

   METHOD="${METHOD:1:${#METHOD}-1}"
   METHODID="`"${MULLE_OBJC_UNIQUEID}" "${METHOD}"`"

   echo "${CLASSID};${CLASS};${CATEGORYID};${CATEGORY};${METHODID};${PREFIX}${METHOD}"
}



_init()
{
   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
   then
      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
      [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
         echo "mulle-bashfunctions-env not installed" >&2 && \
         exit 1
   fi

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   set -o pipefail
}

#
# leading backslash ? looks like we're getting called from
# mingw via a .BAT or so
#
case "$PATH" in
   '\\'*)
      PATH="`tr '\\' '/' <<< "${PATH}"`"
   ;;
esac

#
# combine all coverage files into one and sort -u it
#

_init "$@"
main "$@"
