#! /usr/bin/env bash
#
#   Copyright (c) 2017 Nat! - Mulle kybernetiK
#   Copyright (c) 2017 Nat! - Codeon GmbH
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#

COVERAGE="${1:-method-coverage.csv}"
METHODS="${2:-methods-list.csv}"

coverage_help()
{
   cat <<EOF
Coverage file \"${COVERAGE}\" not found."
Create it by running your mulle-objc code like so:
MULLE_OBJC_DUMP_COVERAGE="YES" /path/to/binary
EOF
}


methods_help()
{
   cat <<EOF
Method lists file \"${METHODS}\" not found."
Create it by running mulle-objc-list on your code like so:
mulle-objc-list -t /path/to/binary > \"${METHODS}\"
EOF
}


if [ ! -f "${COVERAGE}" ]
then
   coverage_help >&2
   exit 1
fi


if [ ! -f "${METHODS}" ]
then
   coverage_help >&2
   exit 1
fi

remove_inherited_methods()
{
   awk -F ';' '{ if( $1 == $3){ print $0} }'
}


remove_first_two_columns()
{
   cut -d';' -f3- < "${COVERAGE}"
}


case "`uname -s`" in
   Darwin|FreeBSD)
      tmpcoverage="`mktemp "/tmp/coverage.XXXXXXXX"`" || exit 1
   ;;

   *)
      tmpcoverage="`mktemp -t "coverage.XXXXXXXX"`" || exit 1
   ;;
esac


cat "${COVERAGE}" | \
   remove_inherited_methods | \
   remove_first_two_columns | \
   sort -u | "${tmpcoverage}"

fgrep -s -x -v -f"${tmpcoverage}" "${METHODS}"

rm "${tmpcoverage}"
