#! /usr/bin/env mulle-bash
#
#   Copyright (c) 2017 Nat! - Mulle kybernetiK
#   Copyright (c) 2017 Nat! - Codeon GmbH
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#


coverage_help()
{
   cat <<EOF
Coverage file "${COVERAGE}" not found."
Create it by running your mulle-objc code like so:
MULLE_OBJC_COVERAGE="YES" /path/to/binary
EOF
}


methods_help()
{
   cat <<EOF
Method lists file "${METHODS}" not found."
Create it by running mulle-objc-list on your code like so:
mulle-objc-list -t /path/to/binary > \"${METHODS}\"
EOF
}


# remove_inherited_methods()
# {
#    rexekutor awk -F ';' '{ if( $1 == $3 || ! $3){ print $0 } }'
# }
#

remove_last_two_columns()
{
   rexekutor cut -d';' -f1-6 < "${COVERAGE}"
}


main()
{
   local OPTION_KEEP_TMP

   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         --keep-tmp)
            OPTION_KEEP_TMP='YES'
         ;;

         -*)
            fail "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown option \"$1\""
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   COVERAGE="${1:-method-coverage.csv}"
   METHODS="${2:-method-list.csv}"

   if [ ! -f "${COVERAGE}" ]
   then
      coverage_help >&2
      exit 1
   fi

   if [ ! -f "${METHODS}" ]
   then
      methods_help >&2
      exit 1
   fi

   local tmpcoverage

   r_make_tmp_file "coverage"
   tmpcoverage="${RVAL}"

#  remove_inherited_methods | \
   rexekutor cat "${COVERAGE}" | \
      rexekutor sort -u > "${tmpcoverage}"

   local tmpmethods

   r_make_tmp_file "methods"
   tmpmethods="${RVAL}"


#  remove_last_two_columns | \

   rexekutor cat "${METHODS}" | \
      rexekutor sort -u > "${tmpmethods}"

   rexekutor grep -F -s -x -v -f "${tmpcoverage}" "${tmpmethods}"

   if [ "${OPTION_KEEP_TMP}" = 'YES' ]
   then
      log_info "Temporary files \"${tmpcoverage}\" and \"${tmpmethods}\" kept on demand"
   else
      remove_file_if_present "${tmpcoverage}"
      remove_file_if_present "${tmpmethods}"
   fi
}

main ${MULLE_TECHNICAL_FLAGS} "$@"
