/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_list_include_h__
#define _mulle_objc_list_include_h__

// You can tweak the following #include with these commands.
// (Use 315B9D64-1484-402B-AD9E-D8AD1E86AF4B instead of mulle-dlfcn if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-dlfcn no-header`
//    rename:             `mulle-sde dependency|library set mulle-dlfcn include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-dlfcn <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-dlfcn [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-dlfcn [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-dlfcn [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-dlfcn no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-dlfcn/mulle-dlfcn.h>   // mulle-dlfcn

#endif
