/*
 *   This file will be regenerated by `mulle-sde reflect` and any edits will be
 *   lost. Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _mulle_objc_list_include_h__
#define _mulle_objc_list_include_h__

// How to tweak the following mulle-dlfcn #include
//    remove:             `mulle-sourcetree mark mulle-dlfcn no-header`
//    rename:             `mulle-sde dependency|library set mulle-dlfcn include whatever.h`
//    toggle #import:     `mulle-sourcetree mark mulle-dlfcn [no-]import`
//    toggle localheader: `mulle-sourcetree mark mulle-dlfcn [no-]localheader`
//    toggle public:      `mulle-sourcetree mark mulle-dlfcn [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-dlfcn [no-]require`
//    remove for os:      `mulle-sourcetree mark mulle-dlfcn no-os-<osname>`
# if defined( __has_include) && __has_include("mulle-dlfcn.h")
#   include "mulle-dlfcn.h"   // mulle-dlfcn
# else
#   include <mulle-dlfcn/mulle-dlfcn.h>   // mulle-dlfcn
# endif

#endif
