#! /usr/bin/env mulle-bash


main()
{
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         --)
            shift
            break
         ;;

         -*)
            fail "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown option \"$1\""
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   rexekutor mulle-objc-printline mylib
   rexekutor mulle-objc-printline --category mylib MulleObjCLoader
   rexekutor mulle-objc-printline --method -uncoverMe mylib
   rexekutor mulle-objc-printline --method +dependencies --category mylib MulleObjCLoader
}

main ${MULLE_TECHNICAL_FLAGS} "$@"
