/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 56DA5265-C2ED-40DE-90D4-6E13848D7CE6 instead of MulleObjC if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark MulleObjC no-header`
//    rename:              `mulle-sde dependency|library set MulleObjC include whatever.h`
//    reorder:             `mulle-sde dependency move MulleObjC <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjC [no-]import`
//    toggle public:       `mulle-sde dependency mark MulleObjC [no-]public`
//    toggle optional:     `mulle-sde dependency mark MulleObjC [no-]require`
//    remove for platform: `mulle-sde dependency mark MulleObjC no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjC/MulleObjC.h>   // MulleObjC

#ifdef __has_include
# if __has_include( "_mylib-include.h")
#  include "_mylib-include.h"
# endif
#endif

