/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_objc_list__dependencies_h__
#define _mulle_objc_list__dependencies_h__

# if ! defined( __MINGW__)
#  include <dlfcn.h>
# endif

# if defined( __MINGW__)
#  include <psapi.h>
# endif

# include <mulle-objc-runtime/mulle-objc-runtime.h>

#endif
