/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_objc_list_include_h__
#define _mulle_objc_list_include_h__

# if ! defined( __mingw__)
#  include <dlfcn.h>   // dlfcn
# endif

# if defined( __mingw__)
#  include <psapi.h>   // psapi
# endif

#endif
